-- Balloons Assets
BALLOON_ASSETS = {
	{ id = "nanos-world::SM_Balloon_01",		name = "SM_Balloon_01",			image = "assets://nanos-world/Thumbnails/SM_Balloon_01.jpg"			},
	{ id = "nanos-world::SM_Balloon_02",		name = "SM_Balloon_02",			image = "assets://nanos-world/Thumbnails/SM_Balloon_02.jpg"			},
	{ id = "nanos-world::SM_Balloon_03",		name = "SM_Balloon_03",			image = "assets://nanos-world/Thumbnails/SM_Balloon_03.jpg"			},
	{ id = "nanos-world::SM_Balloon_04",		name = "SM_Balloon_04",			image = "assets://nanos-world/Thumbnails/SM_Balloon_04.jpg"			},
	{ id = "nanos-world::SM_Balloon_05",		name = "SM_Balloon_05",			image = "assets://nanos-world/Thumbnails/SM_Balloon_05.jpg"			},
	{ id = "nanos-world::SM_Balloon_06",		name = "SM_Balloon_06",			image = "assets://nanos-world/Thumbnails/SM_Balloon_06.jpg"			},
	{ id = "nanos-world::SM_Balloon_07",		name = "SM_Balloon_07",			image = "assets://nanos-world/Thumbnails/SM_Balloon_07.jpg"			},
	{ id = "nanos-world::SM_Balloon_Dog",		name = "SM_Balloon_Dog",		image = "assets://nanos-world/Thumbnails/SM_Balloon_Dog.jpg"		},
	{ id = "nanos-world::SM_Poop",				name = "SM_Poop",				image = "assets://nanos-world/Thumbnails/SM_Poop.jpg"				},
	{ id = "nanos-world::SM_Error",				name = "SM_Error",				image = "assets://nanos-world/Thumbnails/SM_Error.jpg"				},
	{ id = "nanos-world::SM_Mannequin_Head",	name = "SM_Mannequin_Head",		image = "assets://nanos-world/Thumbnails/SM_Mannequin_Head.jpg"		},
	{ id = "nanos-world::SM_TungTungTungSahur",	name = "SM_TungTungTungSahur",	image = "assets://nanos-world/Thumbnails/SM_TungTungTungSahur.jpg"	},
	{ id = "nanos-world::SM_Emoji_03",			name = "SM_Emoji_03",			image = "assets://nanos-world/Thumbnails/SM_Emoji_03.jpg"			},
	{ id = "nanos-world::SM_Emoji_04",			name = "SM_Emoji_04",			image = "assets://nanos-world/Thumbnails/SM_Emoji_04.jpg"			},
	{ id = "nanos-world::SM_Emoji_06",			name = "SM_Emoji_06",			image = "assets://nanos-world/Thumbnails/SM_Emoji_06.jpg"			},
	{ id = "nanos-world::SM_Emoji_09",			name = "SM_Emoji_09",			image = "assets://nanos-world/Thumbnails/SM_Emoji_09.jpg"			},
	{ id = "nanos-world::SM_Emoji_15",			name = "SM_Emoji_15",			image = "assets://nanos-world/Thumbnails/SM_Emoji_15.jpg"			},
	{ id = "nanos-world::SM_Emoji_20",			name = "SM_Emoji_20",			image = "assets://nanos-world/Thumbnails/SM_Emoji_20.jpg"			},
	{ id = "nanos-world::SM_Emoji_33",			name = "SM_Emoji_33",			image = "assets://nanos-world/Thumbnails/SM_Emoji_33.jpg"			},
	{ id = "nanos-world::SM_Emoji_36",			name = "SM_Emoji_36",			image = "assets://nanos-world/Thumbnails/SM_Emoji_36.jpg"			},
	{ id = "nanos-world::SM_Emoji_38",			name = "SM_Emoji_38",			image = "assets://nanos-world/Thumbnails/SM_Emoji_38.jpg"			},
	{ id = "nanos-world::SM_Emoji_39",			name = "SM_Emoji_39",			image = "assets://nanos-world/Thumbnails/SM_Emoji_39.jpg"			},
	{ id = "nanos-world::SM_Emoji_40",			name = "SM_Emoji_40",			image = "assets://nanos-world/Thumbnails/SM_Emoji_40.jpg"			},
	{ id = "nanos-world::SM_Emoji_45",			name = "SM_Emoji_45",			image = "assets://nanos-world/Thumbnails/SM_Emoji_45.jpg"			},
	{ id = "nanos-world::SM_Emoji_47",			name = "SM_Emoji_47",			image = "assets://nanos-world/Thumbnails/SM_Emoji_47.jpg"			},
	{ id = "nanos-world::SM_Emoji_57",			name = "SM_Emoji_57",			image = "assets://nanos-world/Thumbnails/SM_Emoji_57.jpg"			},
	{ id = "nanos-world::SM_Emoji_59",			name = "SM_Emoji_59",			image = "assets://nanos-world/Thumbnails/SM_Emoji_59.jpg"			},
	{ id = "nanos-world::SM_Emoji_61",			name = "SM_Emoji_61",			image = "assets://nanos-world/Thumbnails/SM_Emoji_61.jpg"			},
	{ id = "nanos-world::SM_Emoji_63",			name = "SM_Emoji_63",			image = "assets://nanos-world/Thumbnails/SM_Emoji_63.jpg"			},
	{ id = "nanos-world::SM_Emoji_68",			name = "SM_Emoji_68",			image = "assets://nanos-world/Thumbnails/SM_Emoji_68.jpg"			},
	{ id = "nanos-world::SM_Emoji_71",			name = "SM_Emoji_71",			image = "assets://nanos-world/Thumbnails/SM_Emoji_71.jpg"			},
	{ id = "nanos-world::SM_Emoji_77",			name = "SM_Emoji_77",			image = "assets://nanos-world/Thumbnails/SM_Emoji_77.jpg"			},
	{ id = "nanos-world::SM_Emoji_80",			name = "SM_Emoji_80",			image = "assets://nanos-world/Thumbnails/SM_Emoji_80.jpg"			},
}